// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/sclevine/cflocal/cf/cmd (interfaces: Forwarder)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
	local "github.com/sclevine/cflocal/local"
)

// Mock of Forwarder interface
type MockForwarder struct {
	ctrl     *gomock.Controller
	recorder *_MockForwarderRecorder
}

// Recorder for MockForwarder (not exported)
type _MockForwarderRecorder struct {
	mock *MockForwarder
}

func NewMockForwarder(ctrl *gomock.Controller) *MockForwarder {
	mock := &MockForwarder{ctrl: ctrl}
	mock.recorder = &_MockForwarderRecorder{mock}
	return mock
}

func (_m *MockForwarder) EXPECT() *_MockForwarderRecorder {
	return _m.recorder
}

func (_m *MockForwarder) Forward(_param0 *local.ForwardConfig) (<-chan string, func(), string, error) {
	ret := _m.ctrl.Call(_m, "Forward", _param0)
	ret0, _ := ret[0].(<-chan string)
	ret1, _ := ret[1].(func())
	ret2, _ := ret[2].(string)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

func (_mr *_MockForwarderRecorder) Forward(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Forward", arg0)
}
