// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/sclevine/cflocal/cf/cmd (interfaces: Stager)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	forge "github.com/sclevine/cflocal/vendor/github.com/sclevine/forge"
	engine "github.com/sclevine/cflocal/vendor/github.com/sclevine/forge/engine"
	reflect "reflect"
)

// MockStager is a mock of Stager interface
type MockStager struct {
	ctrl     *gomock.Controller
	recorder *MockStagerMockRecorder
}

// MockStagerMockRecorder is the mock recorder for MockStager
type MockStagerMockRecorder struct {
	mock *MockStager
}

// NewMockStager creates a new mock instance
func NewMockStager(ctrl *gomock.Controller) *MockStager {
	mock := &MockStager{ctrl: ctrl}
	mock.recorder = &MockStagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockStager) EXPECT() *MockStagerMockRecorder {
	return m.recorder
}

// Download mocks base method
func (m *MockStager) Download(arg0, arg1 string) (engine.Stream, error) {
	ret := m.ctrl.Call(m, "Download", arg0, arg1)
	ret0, _ := ret[0].(engine.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download
func (mr *MockStagerMockRecorder) Download(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockStager)(nil).Download), arg0, arg1)
}

// Stage mocks base method
func (m *MockStager) Stage(arg0 *forge.StageConfig) (engine.Stream, error) {
	ret := m.ctrl.Call(m, "Stage", arg0)
	ret0, _ := ret[0].(engine.Stream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stage indicates an expected call of Stage
func (mr *MockStagerMockRecorder) Stage(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stage", reflect.TypeOf((*MockStager)(nil).Stage), arg0)
}
