// Code generated by MockGen. DO NOT EDIT.
// Source: code.cloudfoundry.org/cflocal/cf (interfaces: Help)

// Package mocks is a generated GoMock package.
package mocks

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockHelp is a mock of Help interface
type MockHelp struct {
	ctrl     *gomock.Controller
	recorder *MockHelpMockRecorder
}

// MockHelpMockRecorder is the mock recorder for MockHelp
type MockHelpMockRecorder struct {
	mock *MockHelp
}

// NewMockHelp creates a new mock instance
func NewMockHelp(ctrl *gomock.Controller) *MockHelp {
	mock := &MockHelp{ctrl: ctrl}
	mock.recorder = &MockHelpMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockHelp) EXPECT() *MockHelpMockRecorder {
	return m.recorder
}

// Long mocks base method
func (m *MockHelp) Long() {
	m.ctrl.Call(m, "Long")
}

// Long indicates an expected call of Long
func (mr *MockHelpMockRecorder) Long() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Long", reflect.TypeOf((*MockHelp)(nil).Long))
}

// Short mocks base method
func (m *MockHelp) Short() {
	m.ctrl.Call(m, "Short")
}

// Short indicates an expected call of Short
func (mr *MockHelpMockRecorder) Short() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Short", reflect.TypeOf((*MockHelp)(nil).Short))
}
