// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/sclevine/cflocal/local (interfaces: Help)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Help interface
type MockHelp struct {
	ctrl     *gomock.Controller
	recorder *_MockHelpRecorder
}

// Recorder for MockHelp (not exported)
type _MockHelpRecorder struct {
	mock *MockHelp
}

func NewMockHelp(ctrl *gomock.Controller) *MockHelp {
	mock := &MockHelp{ctrl: ctrl}
	mock.recorder = &_MockHelpRecorder{mock}
	return mock
}

func (_m *MockHelp) EXPECT() *_MockHelpRecorder {
	return _m.recorder
}

func (_m *MockHelp) Show() error {
	ret := _m.ctrl.Call(_m, "Show")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockHelpRecorder) Show() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Show")
}
