// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/sclevine/cflocal/local (interfaces: Versioner)

package mocks

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Versioner interface
type MockVersioner struct {
	ctrl     *gomock.Controller
	recorder *_MockVersionerRecorder
}

// Recorder for MockVersioner (not exported)
type _MockVersionerRecorder struct {
	mock *MockVersioner
}

func NewMockVersioner(ctrl *gomock.Controller) *MockVersioner {
	mock := &MockVersioner{ctrl: ctrl}
	mock.recorder = &_MockVersionerRecorder{mock}
	return mock
}

func (_m *MockVersioner) EXPECT() *_MockVersionerRecorder {
	return _m.recorder
}

func (_m *MockVersioner) Build(_param0 string, _param1 string) (string, error) {
	ret := _m.ctrl.Call(_m, "Build", _param0, _param1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVersionerRecorder) Build(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Build", arg0, arg1)
}
